from __future__ import annotations
from typing import Dict, List, Tuple

class Member:
    def moment_array(self, axis: str, n: int) -> Tuple[List[float], List[float]]: ...
    def shear_array(self, axis: str, n: int) -> Tuple[List[float], List[float]]: ...
    def axial_array(self, n: int) -> Tuple[List[float], List[float]]: ...
    def torque_array(self, n: int) -> Tuple[List[float], List[float]]: ...
    def deflection_array(self, axis: str, n: int) -> Tuple[List[float], List[float]]: ...
    def min_moment(self, axis: str) -> float: ...
    def max_moment(self, axis: str) -> float: ...
    def min_shear(self, axis: str) -> float: ...
    def max_shear(self, axis: str) -> float: ...
    def min_torque(self) -> float: ...
    def max_torque(self) -> float: ...
    def min_deflection(self, axis: str) -> float: ...
    def max_deflection(self, axis: str) -> float: ...

class FEModel3D:
    members: Dict[str, Member]
    def add_node(self, name: str, x: float, y: float, z: float) -> None: ...
    def add_material(self, name: str, E: float, G: float, nu: float, density: float) -> None: ...
    def add_section(self, name: str, A: float, Iy: float, Iz: float, J: float) -> None: ...
    def add_member(self, name: str, i: str, j: str, material: str, section: str) -> None: ...
    def def_support(self, node: str, *flags: bool) -> None: ...
    def add_member_dist_load(self, name: str, axis: str, wi: float, wf: float) -> None: ...
    def add_node_load(self, node: str, axis: str, value: float) -> None: ...
    def add_member_self_weight(self, axis: str, direction: float) -> None: ...
    def def_releases(self, member: str, **releases: bool) -> None: ...
    def analyze(self) -> None: ...
